#pragma once


namespace MC_OpenGL {


enum class ErrorCode
	{
	NONE,
	ERROR_FRAGMENT_SHADER_COMPILATION_FAILED,
	ERROR_GLAD_LOAD_GL_LOADER,
	ERROR_GLFW_CREATE_WINDOW,
	ERROR_GLFW_WINDOW_IS_NULL,
	ERROR_SHADER_PROGRAM_LINKING_FAILED,
	ERROR_TEXTURE_FAILED_TO_LOAD,
	ERROR_VERTEX_SHADER_COMPILATION_FAILED
	};


}
